### ISSUE TITLE
CUDA standard in CMakeLists.txt

### ISSUE THREAD

**Issue by miroslavjurkech** [prittt/YACCLAB#21]
Hello,

first thank you for the benchmark.

The issue:

Please repair CMakeLists.txt, because project cannot be build. It took me time to figure this out.

Your headers included in .cu files use C++14 features. (std::make_unique namely)
On my system: Debian 10, CUDA 10.1, gcc 8.3, I got error make_unique not in namespace std.
I find out CUDA standard is set separatly from C++ host compiler standard:

https://cmake.org/cmake/help/v3.14/prop_tgt/CUDA_STANDARD.html

By providing CMAKE_CUDA_STANDARD 14, compilation did not raise any errors.

I figured I will post it here, even if I doesn't get fixed, others can see how to repair it.

Thank you for your work.

**Comment by prittt** [comment]
Hi @miroslavjurkech, thank you for your hint! Commit ef27de890056297b58583febbec085c116365c6d should solve the problem, but please let us know if there is still something wrong.

Cheers
