### ISSUE TITLE
New CCL algorithms

### ISSUE THREAD

**Issue by attltb** [prittt/YACCLAB#25]
I'm sorry if this is rude. I'm quite new to github so that I don't know what I'm supposed to do here. 
I want to share a new algorithm I found.

You can find them in my [github page](https://github.com/attltb/UFBL), especially in [this](https://github.com/attltb/UFBL/tree/main/YACCLAB) folder.
My algorithms are available with the names of BRTS, BMRS. (They require to specify a labels solver.)
See also the results I got on my computer [here](https://github.com/attltb/UFBL/tree/main/YACCLAB/Results).
Each algorithm is explained in detail in my github page.

I have no degree or qualification in computer science area. 
I came up with these ideas while optimizing an AI for my own game which is still in progress.
I want to let you know and get advice from you if possible.

Thank you.

**Comment by prittt** [comment]
The two algorithms will be (soon) included in YACCLAB with the next  release 🍻🍻
