### ISSUE TITLE
HCS algorithm

### ISSUE THREAD

**Issue by martinweihrauch** [prittt/YACCLAB#33]
Hi,
do you also have an implementation of this algorithm (HCS):
https://link.springer.com/article/10.1007/s11554-015-0499-1

Best regards

Martin

**Comment by prittt** [comment]
Dear @martinweihrauch, 

the original HCS algorithm has been proposed in 
_L. He, Y. Chao, K. Suzuki. "A run-based two-scan labeling algorithm." IEEE Transactions on Image Processing, 2008._
and is available in YACCLAB under the name RBTS (Run-Based Two Scan algorithm). Specifically, it is implemented within "labeling_he_2008.h" file. 

The HCS algorithm you linked introduces the Euler number calculation to RBTS. If you also need this feature, it should require just minor code changes to RBTS implementation. In case, feel free to pull request your code. 

Hope this helps.

Federico

**Comment by martinweihrauch** [comment]
Thank you!!
Is there any algorithm you would recommend to me for the purpose of
a) get the number connected components and
b) get the number of holes (eg Euler)
?

**Comment by prittt** [comment]
Dear @martinweihrauch, 

I suggest you to use the [OpenCV](https://opencv.org/) library that already allows you to [read images in PBM format](https://docs.opencv.org/4.x/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56) and calculate [connected components](https://docs.opencv.org/4.x/d3/dc0/group__imgproc__shape.html#ga107a78bf7cd25dec05fb4dfc5c9e765f) (and their statistics) with [our fastest algorithm Spaghetti labeling](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9339949): 

_Bolelli, F., Allegretti, S., Baraldi, L., & Grana, C. (2019). Spaghetti labeling: Directed acyclic graphs for block-based connected components labeling. IEEE Transactions on Image Processing, 29, 1999-2012._

_Bolelli F, Allegretti S, Grana C. One DAG to Rule Them All. IEEE Trans Pattern Anal Mach Intell. 2021 Jan 28;PP. doi: 10.1109/TPAMI.2021.3055337. Epub ahead of print. PMID: 33507865._


The only thing that is missing in OpenCV (as far as I know) is the calculation of the Euler number. 

Federico

**Comment by martinweihrauch** [comment]
Ok, again: thank you very much!!
Last question: do you have any hint how to calculate the Euler number?

**Comment by prittt** [comment]
It's extremely inefficient, but you can use the [contour hierarchy](https://docs.opencv.org/4.x/d9/d8b/tutorial_py_contours_hierarchy.html) if you don't want to implement the RBTS variation (HCS) or other algorithms by yourself. e.g.: [https://stackoverflow.com/questions/55446593/how-to-count-objects-depending-on-their-number-of-holes#:~:text=Add%20a%20comment-,1,c%5D%2C%20%2D1%2C%20(0%2C255%2C0)%2C%202](https://stackoverflow.com/questions/55446593/how-to-count-objects-depending-on-their-number-of-holes#:~:text=Add%20a%20comment-,1,c%5D%2C%20%2D1%2C%20(0%2C255%2C0)%2C%202)

If you found the YACCLAB repository helpful don't miss to leave a star 😉.
