### ISSUE TITLE
Problem about "How to include a YACCLAB algorithm into your own project?"

### ISSUE THREAD

**Issue by fengweichangzi** [prittt/YACCLAB#34]
Hello Federico,

very nice project about CCL. 

When I tried to follow your step, I could not use the example code(BBDT_UFPC) correctly.
Maybe the section of  "How to include a YACCLAB algorithm into your own project?" is not complete?

First, I found that I have to add more source files than you described
E.g. file_manager.cc,  volume_util.cc, yacclab_tensor.cc, gpu_mat3.cu

Second, I got the error from "labeling_grana_2010.cc", which shows some Gnuplot error as follows:

Error	LNK2019	unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl GetGnuplotTitle(void)" (?GetGnuplotTitle@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Labeling::GetTitle(void)const " 

Maybe this is about some dll of gnuplot, which I do not know should I add some cc files or dll?

**Comment by fengweichangzi** [comment]
Well, I make it finally. The tip is contain all those source files:
- check_labeling.cc
- file_manager.cc
- system_info.cc
- utilities.cc
- volume_util.cc
- yacclab_tensor.cc
-

**Comment by prittt** [comment]
Dear @fengweichangzi, 

thank you for your interest in YACCLAB. Yes, you are right, the section "How to include a YACCLAB algorithm into your own project?" has been written before the introduction of GPU features and algorithms and now more files are required. I'll update the readme accordingly.

Federico.

**Comment by prittt** [comment]
Hey @all-contributors please add @patrickhwood for bug report.

**Comment by prittt** [comment]
Hey @all-contributors please add @fengweichangzi for bug report.
