### ISSUE TITLE
how can i save the result of cuda algorithm

### ISSUE THREAD

**Issue by feixuedudiao** [prittt/YACCLAB#37]
when i save the result with the above code,the result is black ,i think this is wrong ,how can i do that?
![图片](https://github.com/prittt/YACCLAB/assets/1230847/002a49ac-c732-456d-aa50-a4bc8e9f3847)
the input is 
![图片](https://github.com/prittt/YACCLAB/assets/1230847/7384430b-7216-4604-ba86-b81d70e9baf9)

the output is:
![Set_1_ID_01_Camera_1_Seq_1_video0000 png_ACCL](https://github.com/prittt/YACCLAB/assets/1230847/26342252-5434-40b8-ad18-1c3c684ccfb9)

i used config :
![图片](https://github.com/prittt/YACCLAB/assets/1230847/244cbca6-a14d-442d-9c92-463afd8bd0c8)

also, i imwrite the label image with above code, but the result is nothing as well.
![图片](https://github.com/prittt/YACCLAB/assets/1230847/0c8a9b6c-3865-4ecd-9970-f79d0883a070)

**Comment by prittt** [comment]
Dear @feixuedudiao, thank you for your interest in our project. 

Which version of YACCLAB are you using? I've just downloaded the latest commit in the master branch and the code you are referring to is working fine on my machine: 

![set_1_id_01_camera_1_seq_1_video0000 png_buf_480](https://github.com/prittt/YACCLAB/assets/6863130/53634b08-0087-4fef-b45f-66c6a0893dc4)

My `config.yaml` is configured to run only BUF on the 3DPeS dataset as it seems you are doing. 

Did you set `color_labels.average` to `true` in the config file (`color_labels: {average: true, density: false}`)?

**Comment by stal12** [comment]
Have you checked the correctness of the algorithms, setting `correctness: true` in the config file?
If they are not correct, maybe `nvcc` is generating PTX and binary files for a wrong architecture.
To be safe, you can manually set [CMAKE_CUDA_ARCHITECTURES](https://cmake.org/cmake/help/latest/variable/CMAKE_CUDA_ARCHITECTURES.html)
